# Generated by Django 6.1.1 on 2026-09-29 02:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público único de la orden (UUID4).', unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', help_text='Estado actual de la orden en su ciclo de vida.', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Monto total de la orden al momento del checkout.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total (CLP)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Se completa al pasar a estado PAGADO.', null=True, verbose_name='Fecha de pago')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Se completa al pasar a estado CANCELADO.', null=True, verbose_name='Fecha de cancelación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nombre del producto al momento de la compra.', max_length=200, verbose_name='Nombre del producto (snapshot)')),
                ('product_sku', models.CharField(help_text='SKU del producto al momento de la compra.', max_length=50, verbose_name='SKU (snapshot)')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio del producto congelado al momento del checkout.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario (snapshot)')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='unit_price × quantity (almacenado para consultas rápidas).', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de orden',
                'verbose_name_plural': 'Ítems de orden',
                'db_table': 'orders_orderitem',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
    ]
