# Generated by Django 6.1.1 on 2026-09-29 02:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el carro está abierto para agregar ítems. Al hacer checkout se marca como False y se crea uno nuevo.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(help_text='Usuario propietario del carro (relación 1:1).', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carro de compras',
                'verbose_name_plural': 'Carros de compras',
                'db_table': 'cart_cart',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades solicitadas.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Carro')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem del carro',
                'verbose_name_plural': 'Ítems del carro',
                'db_table': 'cart_cartitem',
                'ordering': ['added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='cart_cart_user_id_5d777a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_cartit_cart_id_4bd8c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
    ]
