# Generated by Django 6.1.1 on 2026-09-29 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto (ej: +56912345678).', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono chileno válido (ej: +56912345678).', regex='^\\+?56?9?\\d{8}$|^\\+?56?\\d{9}$')], verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del usuario (formato 12.345.678-9).', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener un formato válido (ej: 12.345.678-9).', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-?[\\dkK]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador de TI')], db_index=True, default='CLIENTE', help_text='Define los permisos del usuario. CLIENTE: compra y gestiona su carro. ADMIN: gestiona catálogo, inventario y estados de órdenes.', max_length=20, verbose_name='Rol del usuario'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
    ]
