# Generated by Django 6.1.1 on 2026-09-29 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la marca (ej: NVIDIA).', max_length=100, unique=True, verbose_name='Nombre de la marca')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'catalog_brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la categoría (ej: Procesadores).', max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, help_text='Identificador URL-friendly generado automáticamente.', max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la categoría.', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está visible en el catálogo.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'catalog_category',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'), models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único de inventario (Stock Keeping Unit).', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(help_text='Nombre comercial del componente.', max_length=200, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, help_text='Especificaciones técnicas y detalles del producto.', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en pesos chilenos. No puede ser negativo.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario (CLP)')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Unidades físicas en bodega.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('image', models.ImageField(blank=True, help_text='Imagen referencial del producto.', null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está disponible para la venta.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'catalog_product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'), models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_ca0f3c_idx'), models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx')],
            },
        ),
    ]
