# Generated by Django 6.1.1 on 2026-09-30 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Precio en pesos chilenos. No puede ser negativo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario (CLP)'),
        ),
    ]
